/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * WarehouseManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface ZoneDto {
  /** @nullable */
  createdAt?: string | null
  id?: number
  isFinal?: boolean
  /** @nullable */
  markers?: string[] | null
  /** @nullable */
  name?: string | null
}
